### PR TITLE
Save cursor position before indenting line with attributes

### LINKED ISSUE #81: Cursor jumps to start of line when typing curly brace in JSX property
Hi!

Thanks for your work on rjsx-mode.  

I'm encountering an issue adding properties to an element. Curly braces seem to trigger a re-indent of the line and cause the cursor to jump to the beginning of the line.

I've recorded a few different examples here. 

I'm experiencing this issue in Spacemacs, but I've tried to reproduce this in as bare of an emacs configuration as I can.  This is my first time filing an issue with an emacs package, please let me know if there's any additional information that I can provide or if I'm doing something stupid here. 

### rjsx-mode
Opening a curly brace de-indents line, closing a curly re-indents (incorrectly to 2 spaces) and places cursor at the beginning of line.

simplescreenrecorder-2018-09-02_13 48 55

### js2-jsx-mode:
Opening a curly brace de-indents the line, closing doesn't fix it.  Cursor stays in place.

simplescreenrecorder-2018-09-02_13 48 17

## Fixing indent level
I noticed that by default `js-indent-level` is 4, and `sgml-basic-offset` is 2.   I added the following code to init.el to make them equal.

```
(setq-default
 js-indent-level 4
 sgml-basic-offset 4)
```

This seems to fix the indention issues completely in both modes, but `rjsx-mode`'s cursor still jumps to the beginning of the line.

### rjsx-mode
simplescreenrecorder-2018-09-02_13 51 31

### js2-jsx-mode
simplescreenrecorder-2018-09-02_13 51 02

## init.el
```elisp
(require 'package)
(add-to-list 'package-archives '("melpa" . "http://melpa.org/packages/"))

(setq package-list
    '(rjsx-mode))

; activate all the packages
(package-initialize)

; fetch the list of packages available
(unless package-archive-contents
  (package-refresh-contents))

; install the missing packages
(dolist (package package-list)
  (unless (package-installed-p package)
    (package-install package)))
```

## Versions
GNU Emacs 26.1
rjsx-mode: 20180823.1645
js2-mode: 20180724.801

### PR DESCRIPTION
**Pull request by qhuyduong**
Signed-off-by: Huy Duong <qhuyduong@hotmail.com>

Resolve #81

### CODE REVIEW

**Comment by felipeochoa** [comment]
Thanks for this PR. Can you add a couple of tests that this works as intended? Does `save-excursion` actually do the job correctly here? E.g., what if point is at BOL/EOL? Both adding and removing spaces?

**Comment by qhuyduong** [comment]
@felipeochoa sorry but I'm new to emacs actually :). Don't know how to write test yet. It just works fine for me. Can you please help to finish this PR for completeness?

**Comment by felipeochoa** [comment]
Welcome to Emacs! :slightly_smiling_face: If you're up for it, I think this would be an easy place to learn a little elisp. Tests are in the `rjsx-tests.el` file. In a nutshell, you use `ert-deftest` to create a test and `should` to run some assertions. So a test for this might:

1. Create a test buffer (`ert-with-test-buffer`)
2. Insert some text (`insert`)
3. Move point somewhere (`goto-char`)
4. Activate rjsx-mode (`rjsx-mode`)
5. Parse the document (`js2-reparse`)
6. Re-indent the current line (`rjxsx-indent-line`)
7. Assert that point is where you expect it to be (`should`)

**Comment by qhuyduong** [comment]
Hi @felipeochoa , 

Didn't here your feedback for such a long time :)

**Comment by qleguennec** [comment]
@qhuyduong There is a small issue with your changes:

Prior to the change (`|` denotes the point):
```jsx
const foo = () => (
  <div>
    <span>hello</span>|
  </div>
);
```
Type RET:
```jsx
const foo = () => (
  <div>
    <span>hello</span>
    |
  </div>
);
```
as of 5efa9ac:
```jsx
const foo = () => (
  <div>
    <span>hello</span>|
  </div>
);
```
Type RET:
```jsx
const foo = () => (
  <div>
    <span>hello</span>
|
  </div>
);
```

**Comment by qhuyduong** [comment]
Thank you very much @qleguennec. I have pushed the fix for that issue.

**Comment by felipeochoa** [comment]
@qhuyduong Thanks for the help with this one! As I wrote more tests I realized it was a bit more complicated, so in order to get the fix out quickly I just wrote it myself in 68fe4c0.

Thanks again for jumping into the codebase and for your patience with me!

**Pull request closed without merging**
